"""Initial schema with all tables

Revision ID: 2166dfae3917
Revises: 
Create Date: 2025-09-19 10:46:31.172279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2166dfae3917'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_phone_e164'), 'leads', ['phone_e164'], unique=True)
    op.create_index(op.f('ix_leads_telegram_user_id'), 'leads', ['telegram_user_id'], unique=True)
    op.create_table('parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=False),
    sa.Column('brand_oem', sa.String(length=100), nullable=False),
    sa.Column('vehicle_make', sa.String(length=100), nullable=False),
    sa.Column('vehicle_model', sa.String(length=100), nullable=False),
    sa.Column('vehicle_trim', sa.String(length=100), nullable=True),
    sa.Column('model_year_from', sa.Integer(), nullable=True),
    sa.Column('model_year_to', sa.Integer(), nullable=True),
    sa.Column('engine_code', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('oem_code', sa.String(length=100), nullable=True),
    sa.Column('alt_codes', sa.Text(), nullable=True),
    sa.Column('dimensions_specs', sa.Text(), nullable=True),
    sa.Column('compatibility_notes', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('pack_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_category'), 'parts', ['category'], unique=False)
    op.create_index(op.f('ix_parts_id'), 'parts', ['id'], unique=False)
    op.create_index(op.f('ix_parts_oem_code'), 'parts', ['oem_code'], unique=False)
    op.create_index(op.f('ix_parts_part_name'), 'parts', ['part_name'], unique=False)
    op.create_index(op.f('ix_parts_status'), 'parts', ['status'], unique=False)
    op.create_index(op.f('ix_parts_vehicle_model'), 'parts', ['vehicle_model'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_lead_id'), 'orders', ['lead_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('seller_url', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('min_order_qty', sa.Integer(), nullable=True),
    sa.Column('available_qty', sa.Integer(), nullable=True),
    sa.Column('warranty', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index(op.f('ix_prices_part_id'), 'prices', ['part_id'], unique=False)
    op.create_index(op.f('ix_prices_valid_from'), 'prices', ['valid_from'], unique=False)
    op.create_index(op.f('ix_prices_valid_to'), 'prices', ['valid_to'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synonyms_id'), 'synonyms', ['id'], unique=False)
    op.create_index(op.f('ix_synonyms_keyword'), 'synonyms', ['keyword'], unique=False)
    op.create_index(op.f('ix_synonyms_lang'), 'synonyms', ['lang'], unique=False)
    op.create_index(op.f('ix_synonyms_part_id'), 'synonyms', ['part_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('matched_part_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['matched_part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'line_no')
    )
    op.create_index(op.f('ix_order_items_matched_part_id'), 'order_items', ['matched_part_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_matched_part_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_synonyms_part_id'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_lang'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_keyword'), table_name='synonyms')
    op.drop_index(op.f('ix_synonyms_id'), table_name='synonyms')
    op.drop_table('synonyms')
    op.drop_table('settings')
    op.drop_index(op.f('ix_prices_valid_to'), table_name='prices')
    op.drop_index(op.f('ix_prices_valid_from'), table_name='prices')
    op.drop_index(op.f('ix_prices_part_id'), table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_lead_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parts_vehicle_model'), table_name='parts')
    op.drop_index(op.f('ix_parts_status'), table_name='parts')
    op.drop_index(op.f('ix_parts_part_name'), table_name='parts')
    op.drop_index(op.f('ix_parts_oem_code'), table_name='parts')
    op.drop_index(op.f('ix_parts_id'), table_name='parts')
    op.drop_index(op.f('ix_parts_category'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_leads_telegram_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone_e164'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
