"""Add enhanced vehicle models and parts categories

Revision ID: 34e2c2a073ed
Revises: 495ba6e24457
Create Date: 2025-09-20 00:17:14.013268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e2c2a073ed'
down_revision = '495ba6e24457'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_fa', sa.String(length=100), nullable=True),
    sa.Column('name_cn', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['part_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_categories_id'), 'part_categories', ['id'], unique=False)
    op.create_index(op.f('ix_part_categories_name'), 'part_categories', ['name'], unique=False)
    op.create_table('vehicle_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_fa', sa.String(length=100), nullable=True),
    sa.Column('name_cn', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_brands_id'), 'vehicle_brands', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_brands_name'), 'vehicle_brands', ['name'], unique=True)
    op.create_table('part_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=True),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_images_id'), 'part_images', ['id'], unique=False)
    op.create_table('part_specifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('spec_name', sa.String(length=100), nullable=False),
    sa.Column('spec_value', sa.String(length=200), nullable=False),
    sa.Column('spec_unit', sa.String(length=20), nullable=True),
    sa.Column('spec_type', sa.String(length=20), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_specifications_id'), 'part_specifications', ['id'], unique=False)
    op.create_table('vehicle_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_fa', sa.String(length=100), nullable=True),
    sa.Column('name_cn', sa.String(length=100), nullable=True),
    sa.Column('generation', sa.String(length=50), nullable=True),
    sa.Column('body_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['vehicle_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_models_id'), 'vehicle_models', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_models_name'), 'vehicle_models', ['name'], unique=False)
    op.create_table('vehicle_trims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_fa', sa.String(length=100), nullable=True),
    sa.Column('trim_code', sa.String(length=50), nullable=True),
    sa.Column('engine_type', sa.String(length=100), nullable=True),
    sa.Column('engine_code', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('drivetrain', sa.String(length=50), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('year_from', sa.Integer(), nullable=True),
    sa.Column('year_to', sa.Integer(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['vehicle_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_trims_id'), 'vehicle_trims', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_trims_name'), 'vehicle_trims', ['name'], unique=False)
    op.drop_index(op.f('idx_wizard_sessions_user_id'), table_name='wizard_sessions')
    op.create_index(op.f('ix_wizard_sessions_id'), 'wizard_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_wizard_sessions_user_id'), 'wizard_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wizard_sessions_user_id'), table_name='wizard_sessions')
    op.drop_index(op.f('ix_wizard_sessions_id'), table_name='wizard_sessions')
    op.create_index(op.f('idx_wizard_sessions_user_id'), 'wizard_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_vehicle_trims_name'), table_name='vehicle_trims')
    op.drop_index(op.f('ix_vehicle_trims_id'), table_name='vehicle_trims')
    op.drop_table('vehicle_trims')
    op.drop_index(op.f('ix_vehicle_models_name'), table_name='vehicle_models')
    op.drop_index(op.f('ix_vehicle_models_id'), table_name='vehicle_models')
    op.drop_table('vehicle_models')
    op.drop_index(op.f('ix_part_specifications_id'), table_name='part_specifications')
    op.drop_table('part_specifications')
    op.drop_index(op.f('ix_part_images_id'), table_name='part_images')
    op.drop_table('part_images')
    op.drop_index(op.f('ix_vehicle_brands_name'), table_name='vehicle_brands')
    op.drop_index(op.f('ix_vehicle_brands_id'), table_name='vehicle_brands')
    op.drop_table('vehicle_brands')
    op.drop_index(op.f('ix_part_categories_name'), table_name='part_categories')
    op.drop_index(op.f('ix_part_categories_id'), table_name='part_categories')
    op.drop_table('part_categories')
    # ### end Alembic commands ###
